title: CANON PIXMA WIRELESS SETUP
description: How to connect the Canon printer to a wireless router via “cableless setup”, Printer software driver installation instructions and troubleshooting tips.

theme: jekyll-theme-slate
